### ISSUE TITLE
[Review] callables at Dispatcher

### ISSUE THREAD

**Issue by schnittstabil** [mindplay-dk/middleman#10]
The [__invoke PHP Manual](http://php.net/manual/en/language.oop5.magic.php#object.invoke) states that the second case below at [Dispatcher](https://github.com/mindplay-dk/middleman/blob/712098b23e00dcbf9ca93c4416e178388796da15/src/Dispatcher.php#L97-L98) is not necessary:
```php
case is_callable($middleware):
case is_object($middleware) && method_exists($middleware, "__invoke"):
```

**Comment by schnittstabil** [comment]
What a pity, I've hoped that was on purpose and may learn something new – anyway :+1:

**Comment by mindplay-dk** [comment]
Was just there for older versions of PHP where `is_callable()` didn't work for classes implementing `__invoke()` - did a quick test, and it does work with the current minimum PHP version 5.4 :-)
