### ISSUE TITLE
Deprecation notices with 8.4

### ISSUE THREAD

**Issue by bkdotcom** [mindplay-dk/middleman#26]
**example**:

ErrorException: mindplay\middleman\Dispatcher::__construct(): Implicitly marking parameter $resolver as nullable is deprecated, the explicit nullable type must be used instead

**Comment by mindplay-dk** [comment]
release `4.0.4` should fix this

I can't test it since PHP 8.4 isn't supported in CI yet (and I need to eventually migrate the whole CI from Travis to Github actions)

it didn't break anything, so I released it, but let me know if it works?

**Comment by mindplay-dk** [comment]
Tested and working with 8.4 today.
