### ISSUE TITLE
Dispatcher

### ISSUE THREAD

**Issue by visiover** [mindplay-dk/middleman#9]
Shouldn't Dispatcher implement "ServerMiddlewareInterface"  from Interop\Http\Middleware\ServerMiddlewareInterface and not "MiddlewareInterface" ? 

MiddlewareInterface.php doesn't exist anymore in 0.2.1

**Comment by oscarotero** [comment]
Is there plans to update to the latest version? I'd like update [Middlewares](https://github.com/middlewares) and this package is used for testing.

**Comment by mindplay-dk** [comment]
Well, it's a breaking change, and my team is not firmly convinced that dropping support for client middleware is a decision that's going to stick. It seems more like a cop out to type-hunting issues (that can't be properly solved with PHP) than a trade off, and we're just not convinced that this is the final word in that discussion.

I think we're going to bide or time and see what happens.

Until then, we could maybe make this change available on a named branch, but we don't want to do a major release at this stage.

What do you think?

**Comment by oscarotero** [comment]
Ok, I understand. Middleman is a stable package relying in an unestable/experimental interface, so this may be the first of many issues comming up.

Maybe a solution is creating a minimalistic dispatcher in [middlewares/utils](https://github.com/middlewares/utils) for testing purposes. This allows to make tests and updates to the latest version of the interface without affecting to the stability and release cycles of middleman.

What do you think? Do you like to work on `Middlewares\Utils\Dispatcher` ?

**Comment by mindplay-dk** [comment]
A minimalist dispatcher is not a bad idea.

Here's a quick (untested!) stripped-down version of middleman, updated to use `ServerMiddlewareInterface` and `ServerRequestInterface` per the BC break:

https://gist.github.com/mindplay-dk/21a7f5252dfe12aa2f655d21166e2b65

Does that help? (I have too many projects and commitments right now.)

**Comment by oscarotero** [comment]
That's perfect.
Don't worry, I'll take care of this.
Thank you!

**Comment by mindplay-dk** [comment]
We're still not convinced this decision will stick, so we're not upgrading internally to this version of middleman yet, but there is now an unstable `3.0.0` branch you can install, so I'm closing this issue.

The `3.0.0` release-branch will remain unstable until PSR-15 is stable.
